name: ztp_projekt
description: Product development for university project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"
dependencies:
  collection: 1.17.0
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.2
  freezed_annotation: ^2.2.0
  intl: ^0.18.1
  json_serializable: ^6.6.1
  path: ^1.8.2
  path_provider: ^2.0.14
  sqflite: ^2.2.6
  sqflite_common_ffi: ^2.2.2
  sqlite3_flutter_libs: ^0.5.13
  url_launcher: ^6.1.10
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2

flutter:
  uses-material-design: true
